# Generated by Django 4.2.4 on 2023-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('juego_f', models.CharField(max_length=100)),
                ('comentario', models.CharField(default='', max_length=200)),
                ('tiempo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('ano_lanzamiento', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('creador', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('ano_lanzamiento', models.PositiveIntegerField()),
            ],
        ),
    ]
